name: Run Linux.do Script

on:
  schedule:
    - cron: "5 9 * * *" # 每天北京时间 1:05 执行
  workflow_dispatch: # 允许手动触发

jobs:
  run-linux-do-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7
      
    - name: Set up Python
      uses: actions/setup-python@v5.2.0
      with:
        python-version: '3.x' # 选择合适的Python版本
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        pip install selenium requests

    - name: Set up WARP
      uses: fscarmen/warp-on-actions@v1.1
      with:
        stack: dual   # Optional. Support [ ipv4, ipv6, dual ]. Default is dual.

    - name: Run Linux.do script
      env:
        LINUXDO_USERNAME: ${{ secrets.LINUXDO_USERNAME }}
        LINUXDO_PASSWORD: ${{ secrets.LINUXDO_PASSWORD }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        SCROLL_DURATION: 5
      run: |
        python Linux.do.py
